export const STANDARD_CHARGES = [
  {
    "name": "AGENCY CHARGES",
    "short_name": "AGENCY CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "AIR FREIGHT CHARGES",
    "short_name": "AIR FREIGHT CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Nil Rated",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "AIR IMP. FREIGHT CHARGES",
    "short_name": "AIR IMP. FREIGHT CHARGES",
    "sac": "996531",
    "tax_type": "Standard GST",
    "gst_charge_type": "Nil Rated",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BL AMENDMENT CHARGES",
    "short_name": "BL AMENDMENT CHARGES",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BL CHARGES",
    "short_name": "BL CHARGES",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BL CHARGES EXP. OVE.",
    "short_name": "BL CHARGES EXP. OVE.",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BL CHARGES PUR.",
    "short_name": "BL CHARGES PUR.",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BL MANIFEST CHARGES -GST 18%",
    "short_name": "BL MANIFEST CHARGES -GST 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "BOND FORMALITIES CHARGES GST-18%",
    "short_name": "BOND FORMALITIES CHARGES GST-18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CARGO HANDLING AND SERVICES",
    "short_name": "CARGO HANDLING AND SERVICES",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Cargo Handling Charges-18%",
    "short_name": "Cargo Handling Charges-18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CFS CHARGES",
    "short_name": "CFS CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CFS CHARGES GST -18%",
    "short_name": "CFS CHARGES GST -18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CFS CHARGES IGST -18%",
    "short_name": "CFS CHARGES IGST -18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CFS CHRGES IGST -18%",
    "short_name": "CFS CHRGES IGST -18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CLEARANCE CHARGES IGST -18%",
    "short_name": "CLEARANCE CHARGES IGST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CO2 EMISSION CHARGES",
    "short_name": "CO2 EMISSION CHARGES",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONSOLIDATION CHARGES GST-18%",
    "short_name": "CONSOLIDATION CHARGES GST-18%",
    "sac": "996799",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONSOLIDATION CHARGES IGST-18%",
    "short_name": "CONSOLIDATION CHARGES IGST-18%",
    "sac": "996799",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONT. IMBALANCING CHARGES IGST 18%",
    "short_name": "CONT. IMBALANCING CHARGES IGST 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONT. SEAL & MANDATORY USAGE CHARGES",
    "short_name": "CONT. SEAL & MANDATORY USAGE CHARGES",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONT. SEAL CHARGES GST-18%",
    "short_name": "CONT. SEAL CHARGES GST-18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONTAINER IMBALANCE SURCHARGE",
    "short_name": "CONTAINER IMBALANCE SURCHARGE",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONTAINER INSPECTION CHARGES",
    "short_name": "CONTAINER INSPECTION CHARGES",
    "sac": "996799",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "CONTAINER PORT STORAGE",
    "short_name": "CONTAINER PORT STORAGE",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "COURIER CHARGES",
    "short_name": "COURIER CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DEMURRAGE CHARGES",
    "short_name": "DEMURRAGE CHARGES",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DETENTION CHARGES",
    "short_name": "DETENTION CHARGES",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DETENTION CHARGES IGST 18%",
    "short_name": "DETENTION CHARGES IGST 18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DETENTION CHARGES-GST 18%",
    "short_name": "DETENTION CHARGES-GST 18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DO CHARGES  GST -18%",
    "short_name": "DO CHARGES  GST -18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DO CHARGES GST -18%",
    "short_name": "DO CHARGES GST -18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DO CHARGES IGST -18%",
    "short_name": "DO CHARGES IGST -18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DO EXTENSION",
    "short_name": "DO EXTENSION",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DO REVALIDATION",
    "short_name": "DO REVALIDATION",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DOCK DESTUFFING CHARGES-IGST18%",
    "short_name": "DOCK DESTUFFING CHARGES-IGST18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DOCUMENTATION CHARGES",
    "short_name": "DOCUMENTATION CHARGES",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DOCUMENTATION, HANDLING, CONTAINER CLG  GST -18%",
    "short_name": "DOCUMENTATION, HANDLING, CONTAINER CLG  GST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DOCUMENTATION, HANDLING, CONTAINER CLG GST -5%",
    "short_name": "DOCUMENTATION, HANDLING, CONTAINER CLG GST -5%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DOCUMENTATION, HANDLING, CONTAINER CLG IGST -18%",
    "short_name": "DOCUMENTATION, HANDLING, CONTAINER CLG IGST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "DPD REGISTRATION CHARGES- GST 18%",
    "short_name": "DPD REGISTRATION CHARGES- GST 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EX WORKS CHARGES",
    "short_name": "EX WORKS CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EX-WORK CHARGES GST -18%",
    "short_name": "EX-WORK CHARGES GST -18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXAMINATION CHARGES GST-18%",
    "short_name": "EXAMINATION CHARGES GST-18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. AFS CHARGES- GST 18%",
    "short_name": "EXP. AFS CHARGES- GST 18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. BAF CHARGES- GST 18%",
    "short_name": "EXP. BAF CHARGES- GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Exp. Documentation Charges",
    "short_name": "Exp. Documentation Charges",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. EMERGENCY SURCHARGES- GST18%",
    "short_name": "EXP. EMERGENCY SURCHARGES- GST18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. ENS CHARGES- GST 18%",
    "short_name": "EXP. ENS CHARGES- GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. FAF CHARGES- GST 18%",
    "short_name": "EXP. FAF CHARGES- GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. GRI CHARGES- GST 18%",
    "short_name": "EXP. GRI CHARGES- GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXP. PCS CHARGES- GST 18%",
    "short_name": "EXP. PCS CHARGES- GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "EXPORT CONST. FACILITATION & ADMIN CHARGES GST- 18%",
    "short_name": "EXPORT CONST. FACILITATION & ADMIN CHARGES GST- 18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "FCA CHARGES GST-18%",
    "short_name": "FCA CHARGES GST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "FOREIGN EXCHANGE CONVERSION CHARGES GST -18%",
    "short_name": "FOREIGN EXCHANGE CONVERSION CHARGES GST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "FUMIGATION CHARGES Export",
    "short_name": "FUMIGATION CHARGES Export",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Nil Rated",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "FUND TRF AND SWIFT CHARGES GST -18%",
    "short_name": "FUND TRF AND SWIFT CHARGES GST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HANDLING CHARGES",
    "short_name": "HANDLING CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HANDLING CHARGES GST-18%",
    "short_name": "HANDLING CHARGES GST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HANDLING CHARGES IGST-18%",
    "short_name": "HANDLING CHARGES IGST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Handling Expenses",
    "short_name": "Handling Expenses",
    "sac": "998313",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HAULAGE CHARGES GST-18%",
    "short_name": "HAULAGE CHARGES GST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HAULAGE CHARGES IGST-18%",
    "short_name": "HAULAGE CHARGES IGST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "HAZ CHARGES",
    "short_name": "HAZ CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "IGM CHARGES GST-18%",
    "short_name": "IGM CHARGES GST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "IGM CHARGES IGST-18%",
    "short_name": "IGM CHARGES IGST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "IGST SALE 18%",
    "short_name": "IGST SALE 18%",
    "sac": "996713",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "IGST SALE 5%",
    "short_name": "IGST SALE 5%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "INSURANCE CHARGES GST - 18%",
    "short_name": "INSURANCE CHARGES GST - 18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "INSURANCE CHARGES PAID GST -18%",
    "short_name": "INSURANCE CHARGES PAID GST -18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "LATE BL FEE GST-18%",
    "short_name": "LATE BL FEE GST-18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "LATE DO CHARGES",
    "short_name": "LATE DO CHARGES",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "MANIFESTATION CHARGES GST-18%",
    "short_name": "MANIFESTATION CHARGES GST-18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "MUC CHARGES",
    "short_name": "MUC CHARGES",
    "sac": "996799",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Ocean Freight",
    "short_name": "Ocean Freight",
    "sac": "998313",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT CHARGES (OUTSIDE INDIA)",
    "short_name": "OCEAN FREIGHT CHARGES (OUTSIDE INDIA)",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Nil Rated",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT CHARGES EXP. OVE.",
    "short_name": "OCEAN FREIGHT CHARGES EXP. OVE.",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT CHARGES GST -5%",
    "short_name": "OCEAN FREIGHT CHARGES GST -5%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT CHARGES IGST -5%",
    "short_name": "OCEAN FREIGHT CHARGES IGST -5%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT CHARGES PAID GST -5%",
    "short_name": "OCEAN FREIGHT CHARGES PAID GST -5%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OCEAN FREIGHT LOCAL PUR",
    "short_name": "OCEAN FREIGHT LOCAL PUR",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OFF DOCK CHARGES IGST-18%",
    "short_name": "OFF DOCK CHARGES IGST-18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "ON CARRIAGE CHARGES",
    "short_name": "ON CARRIAGE CHARGES",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OPEN TOP HANDLING CHARGES GST- 5%",
    "short_name": "OPEN TOP HANDLING CHARGES GST- 5%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "OVERWEIGHT SURCHARGE IGST-18%",
    "short_name": "OVERWEIGHT SURCHARGE IGST-18%",
    "sac": "996799",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "PACKING CHARGES- GST 18%",
    "short_name": "PACKING CHARGES- GST 18%",
    "sac": "996713",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "PORT CONGESTION CHARGE GST 18%",
    "short_name": "PORT CONGESTION CHARGE GST 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Port Demurrage Charges GST-18%",
    "short_name": "Port Demurrage Charges GST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "PORT STORAGE CHARGES- GST 18%",
    "short_name": "PORT STORAGE CHARGES- GST 18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Disabled"
  },
  {
    "name": "PORT STORAGE GST-18%",
    "short_name": "PORT STORAGE GST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "Rebate Expanses",
    "short_name": "Rebate Expanses",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "REBATE EXPENSES",
    "short_name": "REBATE EXPENSES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "RTO CHARGES",
    "short_name": "RTO CHARGES",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Exempted",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SALE 18 % GST",
    "short_name": "SALE 18 % GST",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SALE 5% GST",
    "short_name": "SALE 5% GST",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 5,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SCANNING CHARGES",
    "short_name": "SCANNING CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SCANNING CHARGES GST- 18%",
    "short_name": "SCANNING CHARGES GST- 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SCANNING CHARGES IGST-18%",
    "short_name": "SCANNING CHARGES IGST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SEA CONSOLE MANIFEST",
    "short_name": "SEA CONSOLE MANIFEST",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SECURITY DEPOSIT",
    "short_name": "SECURITY DEPOSIT",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Nil Rated",
    "percentage": 0,
    "gst": 0,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SHIPPING LINE CHARGES EXP. OVE.",
    "short_name": "SHIPPING LINE CHARGES EXP. OVE.",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SHIPPING LINE CHARGES GST -18%",
    "short_name": "SHIPPING LINE CHARGES GST -18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SHIPPING LINE CHARGES IGST -18%",
    "short_name": "SHIPPING LINE CHARGES IGST -18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SHIPPING LINE LOCAL CHARGES",
    "short_name": "SHIPPING LINE LOCAL CHARGES",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SPECIAL EQUIPMENT CHARGES GST 18%",
    "short_name": "SPECIAL EQUIPMENT CHARGES GST 18%",
    "sac": "996521",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "STAMP DUTY - 0%",
    "short_name": "STAMP DUTY - 0%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SUPPORTING SERVICES GST-18%",
    "short_name": "SUPPORTING SERVICES GST-18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SURRENDER BL CHARGES -GST18%",
    "short_name": "SURRENDER BL CHARGES -GST18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SWITCH BL CHARGES EXP. OVE.",
    "short_name": "SWITCH BL CHARGES EXP. OVE.",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "SWITCH BL CHARGES PUR",
    "short_name": "SWITCH BL CHARGES PUR",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TDS FOR PURCHASE",
    "short_name": "TDS FOR PURCHASE",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TERMINAL HANDLING CHARGES GST-18%",
    "short_name": "TERMINAL HANDLING CHARGES GST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TERMINAL HANDLING CHARGES IGST",
    "short_name": "TERMINAL HANDLING CHARGES IGST",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TERMINATION HANDLINE CHARGES PUR",
    "short_name": "TERMINATION HANDLINE CHARGES PUR",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "THC CHARGES",
    "short_name": "THC CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "THC GST - 18%",
    "short_name": "THC GST - 18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "Yes",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "THC IGST-18%",
    "short_name": "THC IGST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TOLL CHARGES GST-18%",
    "short_name": "TOLL CHARGES GST-18%",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TRANSPORATION CHARGES",
    "short_name": "TRANSPORATION CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 12,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "TRANSPORTATION CHARGES IGST-18%",
    "short_name": "TRANSPORTATION CHARGES IGST-18%",
    "sac": "996511",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "VESSEL CERTIFICATE CHARGES GST-18%",
    "short_name": "VESSEL CERTIFICATE CHARGES GST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "VGM CHARGES",
    "short_name": "VGM CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "VGM CHARGES GST-18%",
    "short_name": "VGM CHARGES GST-18%",
    "sac": "996759",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "WEIGHMENT CHARGES GST-18%",
    "short_name": "WEIGHMENT CHARGES GST-18%",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "WEIGHTMENT CHARGES",
    "short_name": "WEIGHTMENT CHARGES",
    "sac": "",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "WEIGHTMENT CHARGES IGST-18%",
    "short_name": "WEIGHTMENT CHARGES IGST-18%",
    "sac": "996719",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Enabled"
  },
  {
    "name": "WRONG",
    "short_name": "WRONG",
    "sac": "996711",
    "tax_type": "Standard GST",
    "gst_charge_type": "Taxable",
    "percentage": 18,
    "gst": 1,
    "igst": 0,
    "rcm": "No",
    "tds_applicable": "No",
    "reimbursement_applicable": "No",
    "status": "Disabled"
  }
];
